import = ["~/.config/alacritty/themes/themes/coolnight.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

[font]
size = 18

normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"

bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"

bold_italic.family = "JetBrainsMono Nerd Font"
bold_italic.style = "Bold Italic"

italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"

[scrolling]
history = 10000
multiplier = 3


[mouse]
#hide_when_typing = true

[selection]
save_to_clipboard = false

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false

[colors]
cursor.text = "0x181818"
cursor.cursor = "0xd8d8d8"
